# Zsh config:
#############

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load .bashrc where all compatible defaults are stored:
# Environment variables
# General startup settings (dircolors, etc)
source .bashrc
limit coredumpsize unlimited

# History configuration:
export HISTFILE=~/.zsh_history
export HISTSIZE=5000
export SAVEHIST=5000

setopt hist_ignore_all_dups # Do not keep duplicate entries
setopt hist_find_no_dups    # Do not show dupplicates, when searching
setopt hist_no_store        # Do not store history commands (fc)
setopt hist_no_functions    # Do not store function definitions
setopt hist_ignore_space    # Do not store commands, which start with a space


# Load modules
autoload -U compinit promptinit
compinit
promptinit


# Completion rules:
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always

zstyle ':completion:*:cd:*' force-list always

zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:warnings' format 'Sorry, no matches for: %B%d%b'


# Setting up prompt:
prompt walters


# Command aliasses:
alias ls='ls --color=always'
alias g='gvim --remote-silent'
alias mplayeri='rlwrap -c -f ~/dotfiles/rlwrap/mplayer.rlwrap mplayer -slave -quiet -idle'
alias tclshi='rlwrap -c -f ~/dotfiles/rlwrap/tcl8.6.rlwrap tclsh'


# Suffix aliasses:
alias -s txt=$EDITOR
alias -s tex=$EDITOR
alias -s c=$EDITOR
alias -s java=$EDITOR
alias -s hs=$EDITOR
alias -s lhs=$EDITOR

alias -s html=$BROWSER
alias -s pdf='xpdf'

alias -s jpg='feh -.'
alias -s png='feh -.'
alias -s gif='feh -.'

alias -s avi='mplayer'


# Key binds:
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward


# Oh-My-Zsh configuration:
#ZSH=$HOME/.oh-my-zsh
#plugin=(git)
#source $ZSH/oh-my-zsh.sh

